# Generated by Django 2.2 on 2020-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
    ]
