# Generated by Django 2.2 on 2020-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0003_auto_20200325_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='identity',
            field=models.CharField(choices=[('学生', '学生'), ('老师', '老师'), ('管理员', '管理员')], default='学生', max_length=10, verbose_name='身份'),
        ),
    ]
