# Generated by Django 2.2 on 2020-04-14 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=11, verbose_name='学生学号')),
                ('sname', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('presentation', models.TextField(max_length=500, verbose_name='学生简介')),
                ('englishChoice', models.CharField(choices=[('四级', '四级'), ('六级', '六级')], default='四级', max_length=2, verbose_name='四级/六级')),
                ('cetImage', models.ImageField(blank=True, upload_to='ETCImage', verbose_name='四级/六级图片')),
                ('cetstatus', models.BooleanField(default=False, verbose_name='使用状态')),
                ('academicActivityText', models.CharField(max_length=500, verbose_name='参与学术活动介绍')),
                ('publicationsText', models.CharField(max_length=500, verbose_name='发表论文介绍')),
                ('participateItemsText', models.CharField(max_length=500, verbose_name='参与项目介绍')),
                ('researchProjectsText', models.CharField(max_length=500, verbose_name='科研项目介绍')),
                ('innovationProjectsText', models.CharField(max_length=500, verbose_name='研究生创新项目介绍')),
                ('socialWorkText', models.CharField(max_length=500, verbose_name='社会服务介绍')),
                ('otherstatus', models.BooleanField(default=False, verbose_name='是否被评分')),
                ('tootherstatus', models.BooleanField(default=False, verbose_name='是否评分')),
                ('judgesGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='评委赋分')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('evaluate', models.TextField(max_length=200, verbose_name='说明')),
                ('activity', models.BooleanField(default=False, verbose_name='导师审核状态')),
            ],
            options={
                'verbose_name': '申请表',
                'verbose_name_plural': '申请表',
            },
        ),
        migrations.CreateModel(
            name='File1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('file', models.FileField(upload_to='testFile', verbose_name='文件')),
            ],
        ),
        migrations.CreateModel(
            name='FuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='赋分表名称')),
            ],
            options={
                'verbose_name': '赋分表',
                'verbose_name_plural': '赋分表',
            },
        ),
        migrations.CreateModel(
            name='GrantLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('money', models.IntegerField(verbose_name='金额')),
                ('text', models.TextField(blank=True, max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '奖助学金等级',
                'verbose_name_plural': '奖助学金等级',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jno', models.CharField(max_length=20, verbose_name='姓名')),
                ('jname', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='id')),
            ],
            options={
                'verbose_name': '评委',
                'verbose_name_plural': '评委',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='申请会议名称')),
                ('endTime', models.DateTimeField(verbose_name='申请结束时间')),
                ('gradeStatus', models.CharField(choices=[('未开始', '未开始'), ('已开始', '已开始'), ('已结束', '已结束')], default='未开始', max_length=10, verbose_name='评分状态')),
                ('jury', models.ManyToManyField(blank=True, to='dataManagement.Jury', verbose_name='评委老师')),
                ('referTeacher', models.ManyToManyField(blank=True, related_name='submit_teacher', to='dataManagement.Jury', verbose_name='已提交评委')),
            ],
            options={
                'verbose_name': '评审会议',
                'verbose_name_plural': '评审会议',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='内容')),
                ('message_type', models.CharField(choices=[('公告通知', '公告通知'), ('评审通知', '评审通知'), ('结果通知', '结果通知')], max_length=4, verbose_name='公告类型')),
                ('show', models.BooleanField(verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='姓名')),
                ('sno', models.CharField(max_length=11, verbose_name='学号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tno', models.CharField(max_length=12, verbose_name='工号')),
                ('tname', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='', max_length=2, null=True, verbose_name='性别')),
                ('register_status', models.BooleanField(default=False, verbose_name='是否注册用户')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=12, verbose_name='学号')),
                ('sname', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='', max_length=2, null=True, verbose_name='性别')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name='入学年月')),
                ('CET4Count', models.SmallIntegerField(default=0, verbose_name='四级使用次数')),
                ('CET6Count', models.SmallIntegerField(default=0, verbose_name='六级使用次数')),
                ('registerStatus', models.BooleanField(default=False, verbose_name='是否注册用户')),
                ('admissionstatus', models.CharField(default='自考', max_length=20, verbose_name='入学身份')),
                ('status', models.BooleanField(default=True, verbose_name='申请资格')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_teacher', to='dataManagement.Teacher', verbose_name='导师')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='SocialWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('socialWorkImage', models.ImageField(upload_to='socialWorkImage', verbose_name='相关图片')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_socialWorkImage', to='dataManagement.ApplicationForm')),
            ],
            options={
                'verbose_name': '社会服务文件',
                'verbose_name_plural': '社会服务文件',
            },
        ),
        migrations.CreateModel(
            name='ResearchProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('researchProjectsImage', models.ImageField(upload_to='researchProjectsImage', verbose_name='相关图片')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_researchProjectsImage', to='dataManagement.ApplicationForm')),
            ],
            options={
                'verbose_name': '参与项目文件',
                'verbose_name_plural': '参与项目文件',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('publicationsImage', models.ImageField(upload_to='publicationsImage', verbose_name='相关图片')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_publicationsImage', to='dataManagement.ApplicationForm')),
            ],
            options={
                'verbose_name': '发表论文文件',
                'verbose_name_plural': '发表论文文件',
            },
        ),
        migrations.CreateModel(
            name='ParticipateItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('participateItemsImage', models.ImageField(upload_to='participateItemsImage', verbose_name='相关图片')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_participateItemsImage', to='dataManagement.ApplicationForm')),
            ],
            options={
                'verbose_name': '参与项目文件',
                'verbose_name_plural': '参与项目文件',
            },
        ),
        migrations.CreateModel(
            name='OtherStudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='学生评分')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.Student', verbose_name='评分学生')),
            ],
            options={
                'verbose_name': '学生互评',
                'verbose_name_plural': '学生互评',
            },
        ),
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='notice', verbose_name='文件')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_files', to='dataManagement.Notice')),
            ],
            options={
                'verbose_name': '公告文件',
                'verbose_name_plural': '公告文件',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='信息内容')),
                ('status', models.BooleanField(default=False, verbose_name='已读')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_message', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='MentorGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='导师评分')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议')),
            ],
            options={
                'verbose_name': '导师评分',
                'verbose_name_plural': '导师评分',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='meeting_student', to='dataManagement.Student', verbose_name='参与学生'),
        ),
        migrations.CreateModel(
            name='InnovationProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('innovationProjectsImage', models.ImageField(upload_to='innovationProjectsImage', verbose_name='相关图片')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_innovationProjectsImage', to='dataManagement.ApplicationForm')),
            ],
            options={
                'verbose_name': '研究生创新项目文件',
                'verbose_name_plural': '研究生创新项目文件',
            },
        ),
        migrations.CreateModel(
            name='AssignItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='赋分项')),
                ('grade', models.IntegerField(verbose_name='分数')),
                ('scoring', models.TextField(max_length=300, verbose_name='赋分标准')),
                ('state', models.TextField(max_length=300, verbose_name='说明')),
                ('show', models.BooleanField(default=True, verbose_name='是否让评委为其赋分')),
                ('fuTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuItem', to='dataManagement.FuTable')),
            ],
            options={
                'verbose_name': '赋分项列表',
                'verbose_name_plural': '赋分项列表',
            },
        ),
        migrations.CreateModel(
            name='ApplicationGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='赋分项')),
                ('grade', models.SmallIntegerField(verbose_name='分数')),
                ('chief_umpire', models.BooleanField(default=False, verbose_name='主审')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationForm_grade', to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_for_application_grade', to='dataManagement.Meeting', verbose_name='会议')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jury_for_application_grade', to='dataManagement.Jury', verbose_name='评委老师')),
            ],
            options={
                'verbose_name': '申请表成绩',
                'verbose_name_plural': '申请表成绩',
            },
        ),
        migrations.AddField(
            model_name='applicationform',
            name='fuTable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.FuTable', verbose_name='赋分表'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.GrantLevel', verbose_name='等级'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.Jury', verbose_name='主审评委'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_for_applicationform', to='dataManagement.Meeting', verbose_name='所属会议'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applicationform', to='dataManagement.Student', verbose_name='学生'),
        ),
        migrations.CreateModel(
            name='AcademicActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('academicActivityImage', models.ImageField(upload_to='academicActivityImage', verbose_name='相关图片')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academicActivityImage', to='dataManagement.ApplicationForm')),
            ],
            options={
                'verbose_name': '学术活动文件',
                'verbose_name_plural': '学术活动文件',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('sno', models.CharField(max_length=11, verbose_name='学生学号')),
                ('text', models.TextField(default='无', max_length=200, verbose_name='原因')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_for_student', to='dataManagement.Meeting', verbose_name='相关会议')),
            ],
            options={
                'verbose_name': '不符合资格学生',
                'verbose_name_plural': '不符合资格学生',
                'unique_together': {('meeting', 'sname')},
            },
        ),
    ]
