# Generated by Django 2.2 on 2020-03-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'verbose_name': '学生互评', 'verbose_name_plural': '学生互评'},
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='academicActivityGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='baseGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='englishGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='innovationProjectsGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='mentorGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='otherGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='participateItemsGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='publicationsGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='researchProjectsGrade',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='socialWorkGrade',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='sno',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='applicationForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.ApplicationForm', verbose_name='申请表'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='otherGrade',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='学生评分'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.Student', verbose_name='评分学生'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.Teacher', verbose_name='主审评委'),
        ),
        migrations.CreateModel(
            name='MentorGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='导师评分')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议')),
            ],
            options={
                'verbose_name': '导师评分',
                'verbose_name_plural': '导师评分',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishGrade', models.IntegerField(verbose_name='四级/六级分数')),
                ('baseGrade', models.SmallIntegerField(default=10, verbose_name='基本分')),
                ('academicActivityGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='学术活动分数')),
                ('publicationsGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='发表论文分数')),
                ('participateItemsGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='参与项目分数')),
                ('researchProjectsGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='科研项目分数')),
                ('innovationProjectsGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='研究生创新项目分数')),
                ('socialWorkGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='社会服务分数')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.Teacher', verbose_name='评委老师')),
            ],
            options={
                'verbose_name': '成绩表',
                'verbose_name_plural': '成绩表',
            },
        ),
    ]
