# Generated by Django 2.2 on 2020-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='evaluate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='jury',
            name='jno',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
