# Generated by Django 2.2 on 2020-03-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0002_auto_20200321_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='applicationForm',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='otherGrade',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='sname',
            field=models.CharField(default=1, max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='sno',
            field=models.CharField(default=1, max_length=11, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='applicationForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationForm_grade', to='dataManagement.ApplicationForm', verbose_name='申请表'),
        ),
        migrations.CreateModel(
            name='OtherStudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherGrade', models.SmallIntegerField(blank=True, null=True, verbose_name='学生评分')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataManagement.Student', verbose_name='评分学生')),
            ],
            options={
                'verbose_name': '学生互评',
                'verbose_name_plural': '学生互评',
            },
        ),
    ]
