# Generated by Django 2.2 on 2020-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0002_auto_20200414_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='all_status',
            field=models.BooleanField(default=False, verbose_name='全部是否提交'),
        ),
        migrations.AddField(
            model_name='jury',
            name='chief_umpire_status',
            field=models.BooleanField(default=False, verbose_name='主审是否提交'),
        ),
    ]
