# Generated by Django 2.2 on 2020-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0003_auto_20200321_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='englishGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='四级/六级分数'),
        ),
    ]
