# Generated by Django 2.2 on 2020-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0004_auto_20200325_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='meeting_student', to='dataManagement.Student', verbose_name='参与学生'),
        ),
    ]
