# Generated by Django 2.2 on 2020-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0004_remove_jury_chief_umpire_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='all_status',
            field=models.CharField(choices=[('未提交', '未提交'), ('已提交', '已提交')], default='未提交', max_length=3, verbose_name='全部是否提交'),
        ),
    ]
