# Generated by Django 2.2 on 2020-03-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0005_auto_20200326_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='otherstatus',
            field=models.BooleanField(default=False, verbose_name='学生互评状态'),
        ),
    ]
