# Generated by Django 2.2 on 2020-04-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0005_auto_20200414_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='all_status',
        ),
    ]
