# Generated by Django 2.2 on 2020-03-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0006_auto_20200328_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participateitems',
            old_name='publicationsImage',
            new_name='participateItemsImage',
        ),
    ]
