# Generated by Django 2.2 on 2020-03-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0007_auto_20200330_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovationprojects',
            old_name='innovationProjects',
            new_name='applicationForm',
        ),
        migrations.RenameField(
            model_name='participateitems',
            old_name='participateItems',
            new_name='applicationForm',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='publications',
            new_name='applicationForm',
        ),
        migrations.RenameField(
            model_name='researchprojects',
            old_name='researchProjects',
            new_name='applicationForm',
        ),
        migrations.RenameField(
            model_name='socialwork',
            old_name='socialWork',
            new_name='applicationForm',
        ),
    ]
