# Generated by Django 2.2 on 2020-04-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0007_jury_all_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='all_status',
        ),
    ]
