# Generated by Django 2.2 on 2020-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0009_auto_20200331_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='cetstatus',
            field=models.BooleanField(default=False, verbose_name='使用状态'),
        ),
    ]
