# Generated by Django 2.2 on 2020-04-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0009_auto_20200415_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='referTeacher',
        ),
    ]
