# Generated by Django 2.2 on 2020-04-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0010_remove_meeting_referteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='grade1',
            field=models.IntegerField(default=1, verbose_name='课程平均成绩/考研成绩'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade2',
            field=models.IntegerField(default=1, verbose_name='复试成绩/开题成绩'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.Meeting', verbose_name='会议'),
            preserve_default=False,
        ),
    ]
