# Generated by Django 2.2 on 2020-04-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0010_applicationform_cetstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='tootherstatus',
            field=models.BooleanField(default=False, verbose_name='是否评分'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='otherstatus',
            field=models.BooleanField(default=False, verbose_name='是否被评分'),
        ),
    ]
