# Generated by Django 2.2 on 2020-04-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0011_auto_20200415_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_student_grade', to='dataManagement.Meeting', verbose_name='会议'),
        ),
    ]
