# Generated by Django 2.2 on 2020-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0011_auto_20200402_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicactivity',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innovationprojects',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participateitems',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchprojects',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialwork',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
