# Generated by Django 2.2 on 2020-04-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0012_auto_20200402_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignitem',
            name='fuTable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuItem', to='dataManagement.FuTable'),
        ),
    ]
