# Generated by Django 2.2 on 2020-04-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0012_auto_20200415_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'verbose_name': '学生成绩', 'verbose_name_plural': '学生成绩'},
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='grant',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='grant1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant3', to='dataManagement.GrantLevel', unique=True, verbose_name='学业奖学金'),
        ),
    ]
