# Generated by Django 2.2 on 2020-04-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0013_auto_20200402_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='activity',
            field=models.CharField(blank=True, choices=[('通过', '通过'), ('不通过', '不通过')], default='', max_length=3, null=True, verbose_name='导师审核状态'),
        ),
    ]
