# Generated by Django 2.2 on 2020-04-04 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataManagement', '0014_auto_20200404_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='activity',
            field=models.BooleanField(default=False, verbose_name='导师审核状态'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='信息内容')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('form_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_message', to=settings.AUTH_USER_MODEL, verbose_name='接收这')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
    ]
