# Generated by Django 2.2 on 2020-04-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0014_auto_20200416_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='grant1',
            new_name='grant',
        ),
    ]
