# Generated by Django 2.2 on 2020-04-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0015_auto_20200416_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant1', to='dataManagement.GrantLevel', verbose_name='国家级/自治区级奖学金'),
        ),
    ]
