# Generated by Django 2.2 on 2020-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0015_auto_20200404_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '申请表成绩', 'verbose_name_plural': '申请表成绩'},
        ),
        migrations.AddField(
            model_name='meeting',
            name='referCount',
            field=models.SmallIntegerField(default=0, verbose_name='评委提交人数'),
        ),
    ]
