# Generated by Django 2.2 on 2020-04-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0016_auto_20200405_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='englishGrade',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='四级/六级分数'),
        ),
    ]
