# Generated by Django 2.2 on 2020-04-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0017_auto_20200405_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='chief_umpire',
            field=models.BooleanField(default=False, verbose_name='主审'),
        ),
    ]
