# Generated by Django 2.2 on 2020-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0017_auto_20200416_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='grant',
            field=models.ManyToManyField(null=True, related_name='other_grant', to='dataManagement.GrantLevel', verbose_name='其他奖助'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='grant1',
            field=models.CharField(choices=[('研究生国家奖学金', '研究生国家奖学金'), ('研究生自治区奖学金', '研究生自治区奖学金'), ('研究生学校奖学金', '研究生学校奖学金')], max_length=20, null=True, verbose_name='国家级/自治区/学校级奖学金'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='grant2',
            field=models.CharField(choices=[('研究生国家助学金', '研究生国家助学金')], max_length=20, null=True, verbose_name='助学金'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='grant3',
            field=models.CharField(choices=[('研究生自治区学业奖学金', '研究生自治区学业奖学金'), ('研究生学校学业奖学金', '研究生学校学业奖学金')], max_length=20, null=True, verbose_name='学业奖学金'),
        ),
    ]
