# Generated by Django 2.2 on 2020-04-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0018_grade_chief_umpire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='赋分项')),
                ('order', models.SmallIntegerField(verbose_name='第几项')),
                ('grade', models.SmallIntegerField(verbose_name='分数')),
                ('chief_umpire', models.BooleanField(default=False, verbose_name='主审')),
                ('applicationForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationForm_grade', to='dataManagement.ApplicationForm', verbose_name='申请表')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_for_application_grade', to='dataManagement.Meeting', verbose_name='会议')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jury_for_application_grade', to='dataManagement.Teacher', verbose_name='评委老师')),
            ],
            options={
                'verbose_name': '申请表成绩',
                'verbose_name_plural': '申请表成绩',
            },
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
