# Generated by Django 2.2 on 2020-04-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0019_auto_20200410_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgrade',
            name='title',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.FuTable', verbose_name='赋分项'),
        ),
    ]
