# Generated by Django 2.2 on 2020-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0020_auto_20200410_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgrade',
            name='title',
            field=models.CharField(max_length=100, verbose_name='赋分项'),
        ),
    ]
