# Generated by Django 2.2 on 2020-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0020_applicationform_grant1'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='grant2',
            field=models.CharField(choices=[('研究生国家助学金', '研究生国家助学金')], max_length=20, null=True, verbose_name='助学金'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='grant3',
            field=models.CharField(choices=[('研究生自治区学业奖学金', '研究生自治区学业奖学金'), ('研究生学校学业奖学金', '研究生学校学业奖学金')], max_length=20, null=True, verbose_name='学业奖学金'),
        ),
    ]
