# Generated by Django 2.2 on 2020-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0021_auto_20200410_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='referCount',
        ),
        migrations.AddField(
            model_name='meeting',
            name='referCount',
            field=models.ManyToManyField(related_name='submit_teacher', to='dataManagement.Teacher', verbose_name='已提交评委'),
        ),
    ]
