# Generated by Django 2.2 on 2020-04-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0022_auto_20200410_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='referCount',
            new_name='referTeacher',
        ),
    ]
