# Generated by Django 2.2 on 2020-04-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0023_remove_applicationform_judgesgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='judgesGrade',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='评委赋分'),
        ),
    ]
