# Generated by Django 2.2 on 2020-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0023_auto_20200410_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignitem',
            name='show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
