# Generated by Django 2.2 on 2020-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0024_assignitem_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationgrade',
            name='order',
        ),
        migrations.AlterField(
            model_name='assignitem',
            name='show',
            field=models.BooleanField(default=True, verbose_name='是否让评委为其赋分'),
        ),
    ]
