# Generated by Django 2.2 on 2020-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0024_applicationform_judgesgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantlevel',
            options={'verbose_name': '其他奖助等级', 'verbose_name_plural': '其他奖助等级'},
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='grant1',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='grant2',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='grant3',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='grant',
            field=models.ManyToManyField(blank=True, related_name='other_grant', to='dataManagement.GrantLevel', verbose_name='奖助等级'),
        ),
    ]
