# Generated by Django 2.2 on 2020-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0025_auto_20200416_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='judgesGrade',
        ),
        migrations.AddField(
            model_name='grantlevel',
            name='sort',
            field=models.CharField(default=1, max_length=100, verbose_name='类别'),
            preserve_default=False,
        ),
    ]
