# Generated by Django 2.2 on 2020-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0027_applicationgrade_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='referTeacher',
            field=models.ManyToManyField(blank=True, related_name='submit_teacher', to='dataManagement.Teacher', verbose_name='已提交评委'),
        ),
    ]
