# Generated by Django 2.2 on 2020-04-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0027_teacher_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantlevel',
            options={'verbose_name': '奖助等级', 'verbose_name_plural': '奖助等级'},
        ),
    ]
