# Generated by Django 2.2 on 2020-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0028_auto_20200411_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=200, verbose_name='信息内容'),
        ),
    ]
