# Generated by Django 2.2 on 2020-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0028_auto_20200417_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade1', models.IntegerField(blank=True, verbose_name='评委平均分')),
                ('grade2', models.IntegerField(blank=True, verbose_name='学生互评分')),
                ('grade3', models.IntegerField(blank=True, verbose_name='导师评分')),
            ],
        ),
    ]
