# Generated by Django 2.2 on 2020-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0029_auto_20200411_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, verbose_name='已读'),
        ),
    ]
