# Generated by Django 2.2 on 2020-04-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0029_allgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='allgrade',
            name='applicationForm',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicationFormALLGrade', to='dataManagement.ApplicationForm', verbose_name='申请表'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allgrade',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetingALLGrade', to='dataManagement.Meeting', verbose_name='会议'),
            preserve_default=False,
        ),
    ]
