# Generated by Django 2.2 on 2020-04-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0030_auto_20200411_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
