# Generated by Django 2.2 on 2020-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0030_auto_20200421_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgrade',
            name='grade1',
            field=models.IntegerField(blank=True, null=True, verbose_name='评委平均分'),
        ),
        migrations.AlterField(
            model_name='allgrade',
            name='grade2',
            field=models.IntegerField(blank=True, null=True, verbose_name='学生互评分'),
        ),
        migrations.AlterField(
            model_name='allgrade',
            name='grade3',
            field=models.IntegerField(blank=True, null=True, verbose_name='导师评分'),
        ),
    ]
