# Generated by Django 2.2 on 2020-04-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0031_auto_20200411_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_message', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
    ]
