# Generated by Django 2.2 on 2020-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0032_auto_20200411_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('message_type', models.CharField(choices=[('公告通知', '公告通知'), ('评审通知', '评审通知'), ('结果通知', '结果通知')], max_length=4, verbose_name='公告类型')),
                ('show', models.BooleanField(verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
